"use client";

import React from "react";
import { motion } from "framer-motion";
import { Car, Zap, Droplets, Utensils, ShoppingBag, Smartphone } from "lucide-react";

export function CarbonExplainer() {
  const categories = [
    {
      icon: <Car className="w-5 h-5" />,
      label: "Transport",
      desc: "Driving and flights usually make up the largest chunk of a personal footprint.",
      color: "bg-[#00ff88]",
      textColor: "text-[#00ff88]",
      width: "w-[28%]",
    },
    {
      icon: <Zap className="w-5 h-5" />,
      label: "Energy",
      desc: "Heating, cooling, and powering your home.",
      color: "bg-[#00d4ff]",
      textColor: "text-[#00d4ff]",
      width: "w-[25%]",
    },
    {
      icon: <Utensils className="w-5 h-5" />,
      label: "Food",
      desc: "Meat consumption and food waste drive agricultural emissions.",
      color: "bg-[#ffd700]",
      textColor: "text-[#ffd700]",
      width: "w-[20%]",
    },
    {
      icon: <ShoppingBag className="w-5 h-5" />,
      label: "Shopping",
      desc: "Manufacturing and shipping new goods requires significant energy.",
      color: "bg-[#f97316]",
      textColor: "text-[#f97316]",
      width: "w-[15%]",
    },
    {
      icon: <Smartphone className="w-5 h-5" />,
      label: "Digital",
      desc: "Data centers powering streaming and cloud storage use massive electricity.",
      color: "bg-[#a78bfa]",
      textColor: "text-[#a78bfa]",
      width: "w-[8%]",
    },
    {
      icon: <Droplets className="w-5 h-5" />,
      label: "Water",
      desc: "Treating and pumping water has a hidden carbon cost.",
      color: "bg-[#60a5fa]",
      textColor: "text-[#60a5fa]",
      width: "w-[4%]",
    },
  ];

  return (
    <section 
      className="py-16 relative z-10"
      aria-label="What is a carbon footprint?"
      role="region"
    >
      <div className="max-w-4xl mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            What makes up your footprint?
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            A carbon footprint is the total amount of greenhouse gases generated by our actions. 
            Here&apos;s a typical breakdown of where those emissions come from.
          </p>
        </motion.div>

        {/* Visual Bar */}
        <div className="glass-dark p-6 rounded-2xl mb-8">
          <div className="h-8 w-full rounded-full overflow-hidden flex gap-1 mb-8" aria-hidden="true">
            {categories.map((cat, i) => (
              <motion.div
                key={cat.label}
                initial={{ width: 0 }}
                whileInView={{ width: cat.width.replace("w-[", "").replace("]", "") }}
                viewport={{ once: true }}
                transition={{ duration: 1, delay: i * 0.1 }}
                className={`h-full ${cat.color} opacity-80 hover:opacity-100 transition-opacity cursor-pointer`}
                title={cat.label}
              />
            ))}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {categories.map((cat, i) => (
              <motion.div
                key={cat.label}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="flex items-start gap-4 p-4 rounded-xl hover:bg-white/5 transition-colors"
              >
                <div className={`p-2 rounded-lg bg-white/5 ${cat.textColor}`}>
                  {cat.icon}
                </div>
                <div>
                  <h3 className={`font-semibold mb-1 ${cat.textColor}`}>
                    {cat.label}
                  </h3>
                  <p className="text-sm text-gray-400 leading-relaxed">
                    {cat.desc}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
